spring:
  profiles:
    active:
    - dev    
---
#开发环境
spring:
  profiles: dev        
  application: 
    name: microservicecloud-config-shengjianjia-dev
---
#测试环境
spring:
  profiles: test       
  application: 
    name: microservicecloud-config-shengjianjia-test
    
    
#请以UTF-8格式保存   
